### ISSUE TITLE
release-plz init: check if the local dependencies of public crates have a `version` field

### ISSUE THREAD

**Issue by MarcoIeni** [release-plz/release-plz#1763]
## Motivations

Example error:

```
 2024-10-10T10:30:11.050960Z ERROR  failed to release package

Caused by:
    failed to publish expandable-impl:     Updating crates.io index
    error: all dependencies must have a version specified when publishing.
    dependency `rust-grammar-dpdfa` does not specify a version
    Note: The published dependency will use the version from crates.io,
    the `path` specification will be removed from the dependency declaration.
```

If a dependency has a `path`, it means it's a local dependency.
All local dependencies need to be like this:

```toml
marco-test-one = { path = "crates/marco-test-one", version = "0.3.21" }
```

I.e. if `path` is present, `version` must be present to.

## Solution

Add this check to `release-plz init` and report an error if there's a dependency that doesn't have the `version` field.

You can look the metadata of the packages to check if `version` is present.

**Comment by MarcoIeni** [comment]
Yes 👍

**Comment by Angr1st** [comment]
Thanks for your answer, my next question is do we want to allow every version requirement? My current understanding is if you put no version it should be "*" (wildcard), which I feel like shouldn't be a valid value?

**Comment by MarcoIeni** [comment]
Imo, let's allow every version requirement if it's allowed by cargo (I think it should be, you don't need to check if you don't want to, we can assume `*` is valid).

**Comment by Angr1st** [comment]
So the only thing not allowed is having not Comperator at all?

**Comment by MarcoIeni** [comment]
Yes:

- `marco-test-one = { path = "crates/marco-test-one" }` is bad

- `marco-test-one = { path = "crates/marco-test-one", version = "..." }` is good 👍

**Comment by Angr1st** [comment]
Ok, after testing I found that specifying `version = "*"` is like having no version specified at all which makes sense. 

This would be my suggestion for the error output:

```
   2024-11-19T13:36:22.270870Z ERROR  The following packages have local dependencies missing a version specifier:
- package `task-tui`:
        • local dependency `local` is missing a `version` entry
        • local dependency `local_three` is missing a `version` entry

Note: to disable this check, set the `--no-toml-check` flag.
```

I think this makes it quiet clear what is missing but also duplicates information.

**Comment by Angr1st** [comment]
it mentions local dependency twice once in the first line and then for each entry but if thats fine then. I'll create the PR.
