### ISSUE TITLE
Generated PR switches from pre-release version to stable instead of incrementing

### ISSUE THREAD

**Issue by helgee** [release-plz/release-plz#1914]
## Bug description

The PR generated by the release-plz GHA workflow automatically switches from an alpha version to a stable version (see screenshot below).

- Would you like to work on a fix? _Yes, if I can find the time and it's within my capabilities._

## To Reproduce

1. TBD
2. ...
3. ...
4. ...

## Expected behavior

The alpha version should be incremented.

## Screenshots

<img width="921" alt="grafik" src="https://github.com/user-attachments/assets/c7fb3f66-af29-4dd5-81ee-62bc503f4015" />

## Environment

- OS: `ubuntu-latest`
- release-plz version: `MarcoIeni/release-plz-action@main`

## Additional context

The problem seems to be triggered when a crate has a dependency on another crate in the workspace and the latter is being updated, e.g. in this [PR](https://github.com/lox-space/lox/pull/177).

- `lox-math`: 0.1.0-alpha.2 -> 0.1.0-alpha.3
  - `lox-math` does not have any local dependencies
- `lox-bodies`: 0.1.0-alpha.1 -> 0.1.1
  - `lox-bodies` depends on `lox-math`
  
The changelog for `lox-bodies` is

```diff
+## [0.1.1](https://github.com/lox-space/lox/compare/lox-bodies-v0.1.0-alpha.1...lox-bodies-v0.1.1) - 2024-12-18
+
+### Other
+
+- updated the following local packages: lox-math
+
```

**Comment by MarcoIeni** [comment]
can you create a reproduction?

**Comment by helgee** [comment]
Could this be the offending line? https://github.com/release-plz/release-plz/blob/main/crates/release_plz_core/src/next_ver.rs#L750

**Comment by MarcoIeni** [comment]
yes, exactly! PR welcome 🙏

**Comment by helgee** [comment]
Done 🎉
